on:
  pull_request:
    types: [ closed ]

jobs:
  auto_creat_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to create PR
    steps:
      - name: Auto Create PR
        id: auto_creat_pr
        uses: minhtrong-bic/bic-pr-automation@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}